# Generated by Django 3.0.6 on 2020-05-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_preffered', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('AOI_1', models.CharField(max_length=100)),
                ('AOI_2', models.CharField(max_length=100)),
                ('AOI_3', models.CharField(max_length=100)),
                ('percentage_10', models.IntegerField()),
                ('percentage_12', models.IntegerField()),
                ('percentage_undergrad', models.IntegerField()),
                ('backlogs', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward.Registration')),
            ],
        ),
    ]
