# Generated by Django 3.0.6 on 2020-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0002_cat_gre_cseece_gre_mechanicalcivil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catscore', models.IntegerField()),
                ('academic_percentage', models.FloatField()),
                ('AOI', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GREScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grescore', models.IntegerField()),
                ('ielts_score', models.IntegerField(blank=True)),
                ('toefl', models.IntegerField(blank=True)),
                ('academic_percentage', models.FloatField()),
                ('AOI', models.CharField(max_length=150)),
            ],
        ),
    ]
