# Generated by Django 3.0.6 on 2020-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0004_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileevaluation',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
