# Generated by Django 3.0.6 on 2020-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0006_remove_profileevaluation_aoi_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileResult',
        ),
        migrations.RemoveField(
            model_name='grescore',
            name='ielts_score',
        ),
        migrations.RemoveField(
            model_name='grescore',
            name='toefl',
        ),
        migrations.AlterField(
            model_name='profileevaluation',
            name='backlogs',
            field=models.FloatField(),
        ),
    ]
