# Generated by Django 3.0.6 on 2020-05-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0007_auto_20200513_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_preffered', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forward.Registration')),
            ],
        ),
    ]
