# Generated by Django 3.0.6 on 2020-05-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0009_score1_evaluation_gre_score2_evaluation_gre_score3_evaluation_gre_score4_evaluation_gre_score_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileresult',
            name='name',
        ),
    ]
